### PR TITLE
Replaced static dependencies with bower, closes #1

### LINKED ISSUE #1: Register for bower
It would be great if you could make the dashboard available on bower.

### PR DESCRIPTION
**Pull request by thelfensdrfer**
I "accidentally" changed many lines when I saved the file. My editor automatically removes spaces at the end of the lines. Probably you also want to check if all works as intended. 

If all looks good, you have to create a git tag with the current version and then you can publish the package via `bower register light-bootstrap-dashboard git://github.com/timcreative/light-bootstrap-dashboard.git` (http://bower.io/docs/creating-packages/#register)

### CODE REVIEW

**Comment by alexandru-paduraru** [comment]
That's awesome, we will check it an register to bower then merge them. Thank you for collaboration!

**Comment by alexandru-paduraru** [comment]
Hi, we checked the files and everything is looking good if we take the archive that you made and then run "bower install", everything was fine. But I know there are a lot of users who don't know how to use bower, they just want to download an archive "that works". That's why they like to download from Creative Tim, they receive a product that is working so they don't have too many dependecies and other stuff to install and fix in order to get a working product. How can we make this possible for this users? So they will be able to download the archive and then just to take what is working without running any other commands. 

Thank you for your help!

**Comment by thelfensdrfer** [comment]
This is absolutely right. One idea is to create a zip file every [minor|major] version (including all bower dependencies) and upload it to github releases.

**Comment by alexandru-paduraru** [comment]
That is a good idea, I was thinking if we can create something like Flat UI - https://github.com/designmodo/Flat-UI. If you download it everything seems to work fine. Or should we add a separate folder inside the repo and call it "Beginner Folder" or something like that? What do you think?

**Comment by thelfensdrfer** [comment]
I think it should be enough to just publish the zip as a release. You can then link to it on your website, the readme and everywhere else. In my opinion everyone who wants to create a dashboard should then know how to proceed;)

But that's just my opinion.

**Comment by alexandru-paduraru** [comment]
Yep, you're right :)) 

Who want to get the functional static dashboard can take it from the release archive or from Creative Tim (because we host it there too for the users who don't use github/bower) and who is more advanced can take it with bower. We will add the bower version in the master of light-bootstrap-dashboard. Still have to make some small adjustments.

Thank you for your time and sorry for bothering you.

**Comment by thelfensdrfer** [comment]
No problem. I will use it myself and in the end it saves me a lot of time. So thank YOU;)

**Pull request closed without merging**
